version: '3'
services:
  api:
    container_name: quore
    image: ghcr.io/novators-mobile/quore-api:main
    restart: always
    expose:
      - 8000
    depends_on:
      - postgres
      - traefik
    labels:
      - "traefik.http.routers.api.rule=(PathPrefix(`/api`))"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    command: --interval 30 quore
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${{ secrets.DB_USER }}
      - POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
      - POSTGRES_DB=${{ secrets.DB_NAME }}
  traefik:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  postgres_data:


    
