version: '3'
services:
  api:
    container_name: quore
    image: ghcr.io/novators-mobile/quore-api:main
    expose:
      - 80
    depends_on:
      - postgres
      - s3
  expo:
    container_name: expo
    image: ghcr.io/novators-mobile/quore:master
    ports:
      - 8081:8081
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    command: --interval 30 quore expo
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  s3:
    image: zenko/cloudserver:latest-0.0.0
    container_name: s3
    volumes:
      - s3_data:/usr/src/app/localData
      - s3_metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=quoreapi
      - SCALITY_SECRET_ACCESS_KEY=${S3_SECRET}
      - ENDPOINT=s3
    expose:
      - 8000
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/novatorsmobile_ru.full.crt:/etc/ssl/certs/novatorsmobile_ru.full.crt
      - /etc/ssl/certs/novatorsmobile_ru.key:/etc/ssl/certs/novatorsmobile_ru.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
volumes:
  postgres_data:
  s3_data:
  s3_metadata:


    
