FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

COPY . . 

RUN pip install --no-cache-dir --upgrade -r requirements.txt

ENV MAIL_USERNAME="BLANK"
ENV MAIL_PASSWORD="BLANK"
ENV MAIL_FROM="BLANK"
ENV MAIL_SERVER="BLANK"
ARG JWT_ACCESS_SECRET
ENV JWT_ACCESS_SECRET ${JWT_ACCESS_SECRET}
ARG JWT_REFRESH_SECRET
ENV JWT_REFRESH_SECRET ${JWT_REFRESH_SECRET}
ARG JWT_ALGORITHM
ENV JWT_ALGORITHM ${JWT_ALGORITHM}
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ENV DB_SERVER="postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME}"
