name: Start deploy

on:
  push:
    paths:
      - "docker-compose.yml"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: stop previous version api
        run: docker-compose down
      - name: install new version
        run: docker pull ghcr.io/novators-mobile/quore-api:main
      - name: run api
        run: docker-compose up -d
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}