name: Start deploy

on:
  push:
    paths:
      - "docker-compose.yml"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: stop previous version api
        run: docker-compose down
      - name: build docker image
        run: docker build -t quore-api:local --build-arg JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} --build-arg JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} --build-arg JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }} --build-arg DB_USER=${{ secrets.DB_USER }} --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} --build-arg DB_NAME=${{ secrets.DB_NAME }} .
      - name: run api
        run: docker-compose up -d
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}