name: Start deploy

on:
  push:
    paths:
      - "docker-compose.yml"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: stop previous version api
        run: docker-compose down
      - name: run api
        run: docker-compose up -d
